import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import useBasePath from "../../../../../hooks/useBasePath";
import FormLogEntreSortie from "../../../../../components/supply-and-consumable/[id]/registreStock";

const CreationFournitureConsommable: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>
          Logistiques - Fournitures et consommables - Article - Creer
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <FormLogEntreSortie />
      </Container>
    </BackOfficeLayout>
  );
};

export default CreationFournitureConsommable;
