import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../layouts/backOffice";
import useBasePath from "../../../../hooks/useBasePath";
import BonTransfertForm from "../../../../components/materiels/bon_transfert/add/bonTransfertForm";

const CommandePage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Matériels-bonCommandeInterne-ajouter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <BonTransfertForm />
      </Container>
    </BackOfficeLayout>
  );
};

export default CommandePage;
