import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../layouts/backOffice";
import useBasePath from "../../../hooks/useBasePath";
import BonCommandeExterneList from "../../../components/materiels/bon_commande_externe";

const ListBonCommandeExterne: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Matériels -Bon de commande externe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
          <BonCommandeExterneList />
      </Container>
    </BackOfficeLayout>
  );
};

export default ListBonCommandeExterne;