import React from "react";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import Head from "next/head";
import { Container } from "@mui/material";
import useBasePath from "../../../../../hooks/useBasePath";
import DetailsOrderEquipement from "../../../../../components/materiels/commandes/[id]";

const DetailCommande = () => {
	const basePath = useBasePath();
	return (
		<BackOfficeLayout>
			<Head>
				<title>Logistiques - details - commandes</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href={`${basePath}/favicon.ico`} />
			</Head>
			<Container maxWidth="xl">
				<DetailsOrderEquipement />
			</Container>
		</BackOfficeLayout>
	);
};

export default DetailCommande;
