version: "3.9"
services:
  mvt-front-logistique:
    container_name: mvt-front-logistique
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    networks:
      - mvt-docker-network
    command: npm run start
    restart: always
    expose:
      - 3000
networks:
  mvt-docker-network:
    name: mvt-docker-network
    