import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../layouts/backOffice";
import useBasePath from "../../../hooks/useBasePath";
import BonCommandeInterneList from "../../../components/fournitures_et_consommables/bon_commande_interne";

const ListCommandeFournitureConsommable: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Fourniture et Consommable -Bon de commande interne</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
          <BonCommandeInterneList />
      </Container>
    </BackOfficeLayout>
  );
};

export default ListCommandeFournitureConsommable;