import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import AddMaterielExterne from "../../../../components/materiel_de_transport/location/addMaterielExterne/AddMaterielExterne";
import useBasePath from "../../../../hooks/useBasePath";
import BackOfficeLayout from "../../../../layouts/backOffice";

const TransportPage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques-materiel de transport</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <AddMaterielExterne />
      </Container>
    </BackOfficeLayout>
  );
};

export default TransportPage;
