import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../layouts/backOffice";
import useBasePath from "../../../../hooks/useBasePath";
import ListFormDetationMateriel from "../../../../components/materiels/detenteur/ajouter/ListFormDetationMateriel";

const AddDetenteur: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Detention-ajouter</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <ListFormDetationMateriel />
      </Container>
    </BackOfficeLayout>
  );
};

export default AddDetenteur;
