import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../layouts/backOffice";
import useBasePath from "../../../hooks/useBasePath";
import Passenger from "../../../components/configurations/passenger/Passenger";

const ListFormEtatMateriel: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Configuartion - Etat des matériels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <Passenger />
      </Container>
    </BackOfficeLayout>
  );
};

export default ListFormEtatMateriel;
