import { Container } from "@mui/material";
import Head from "next/head";
import React from "react";
import FicheDeDotationForm from "../../../../../components/materiels/fiche_dotation/add/FichDeDotationForm";
import useBasePath from "../../../../../hooks/useBasePath";
import BackOfficeLayout from "../../../../../layouts/backOffice";
const Edit = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Modifier</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <FicheDeDotationForm/>
      </Container>
    </BackOfficeLayout>
  );
};

export default Edit;

