import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../layouts/backOffice";
import useBasePath from "../../../../hooks/useBasePath";
import CreationFormDemmandeCommandeMateriel from "../../../../components/materiels/commandes/creer/CreationFormDemmandeCommandeMateriel";

const FormDemmandeMaterielEmployerConnecter: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - materiels - commandes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
            <CreationFormDemmandeCommandeMateriel/>
      </Container>
    </BackOfficeLayout>
  );
};

export default   FormDemmandeMaterielEmployerConnecter;





