import React from "react";
import Head from "next/head";
import useBasePath from "../../../../../../hooks/useBasePath";
import BackOfficeLayout from "../../../../../../layouts/backOffice";
import { Container } from "@mui/material";
import FormGestionArticle from "../../../../../../components/materiels/commandes/ajouter/article/FormGestionArticle";

const index = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Gerer Article</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <FormGestionArticle />
      </Container>
    </BackOfficeLayout>
  );
};

export default index;
