import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../../../layouts/backOffice";
import useBasePath from "../../../../../../hooks/useBasePath";
import FormGestionArticle from "../../../../../../components/materiels/commandes/ajouter/article/FormGestionArticle";


const FormulaireGestionArticle: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistique - Commandes - Créer - Offres - Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
            <FormGestionArticle/>
      </Container>
    </BackOfficeLayout>
  );
};

export default FormulaireGestionArticle;

