import React from "react";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import Head from "next/head";
import useBasePath from "../../../../../hooks/useBasePath";
import { Container } from "@mui/material";
import ListFormAfficherCommande from "../../../../../components/materiels/commandes/details/ListCommande";

const index = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - details - commandes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <ListFormAfficherCommande />
      </Container>
    </BackOfficeLayout>
  );
};

export default index;
