import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import useBasePath from "../../../../../hooks/useBasePath";
import DetailsBonReception from "../../../../../components/materiels/bon_reception/[id]/DetailsBon_reception";

const DetailsBonReceptionPage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Fournitures et consommables-articleBon de reception-details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <DetailsBonReception />
      </Container>
    </BackOfficeLayout>
  );
};

export default DetailsBonReceptionPage;
