import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import DetailsVendor from "../../../components/vendor/[id]/DetailsContracts";
import useBasePath from "../../../hooks/useBasePath";
import BackOfficeLayout from "../../../layouts/backOffice";

const EditFournisseur: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Modifier</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <DetailsVendor />
      </Container>
    </BackOfficeLayout>
  );
};

export default EditFournisseur;
