import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import EditFactureConsommation from "../../../../../components/materiel_de_transport/facture_de_consommation/[id]/edit";
import useBasePath from "../../../../../hooks/useBasePath";
import BackOfficeLayout from "../../../../../layouts/backOffice";

const TransportPage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques-materiel de transport</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <EditFactureConsommation></EditFactureConsommation>
      </Container>
    </BackOfficeLayout>
  );
};

export default TransportPage;