import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import FormSuiviCarburant from "../../../../../components/materiel_de_transport/suivi_carburant/add/formSuiviCarburant";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import useBasePath from "../../../../../hooks/useBasePath";
import FormMission from "../../../../../components/materiel_de_transport/mission/add/formMission";

const FormSuiviCarburantPage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Suivi carburant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <FormMission/>
      </Container>
    </BackOfficeLayout>
  );
};

export default FormSuiviCarburantPage;