import React from "react";
import BackOfficeLayout from "../../../../layouts/backOffice";
import Head from "next/head";
import useBasePath from "../../../../hooks/useBasePath";
import { Container } from "@mui/material";
import FormDemandeMateriel from "../../../../components/materiels/mes_commandes/creer/FormDemandeMateriel";

const index = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Creer - Commandes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <FormDemandeMateriel />
      </Container>
    </BackOfficeLayout>
  );
};

export default index;
