import React from "react";
import BackOfficeLayout from "../../../../layouts/backOffice";
import Head from "next/head";
import { Container } from "@mui/material";
import FormDemandeMateriel from "../../../../components/materiels/mes_commandes/creer/FormDemandeMateriel";
import useBasePath from "../../../../hooks/useBasePath";

const CreateMyCommande = () => {
	const basePath = useBasePath();
	return (
		<BackOfficeLayout>
			<Head>
				<title>Logistiques - Creer - Commandes</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href={`${basePath}/favicon.ico`} />
			</Head>
			<Container maxWidth="xl">
				<FormDemandeMateriel />
			</Container>
		</BackOfficeLayout>
	);
};

export default CreateMyCommande;
