import { Container } from "@mui/material";
import Head from "next/head";
import React from "react";
import useBasePath from "../../../../../hooks/useBasePath";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import FormBonCommandeFournisseur from "../../../../../components/materiels/bon_commande_fournisseur/creer/createBonCommandeFournisseur";

const Edit = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Modifier</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <FormBonCommandeFournisseur/>
      </Container>
    </BackOfficeLayout>
  );
};

export default Edit;

