import Head from "next/head";
import type { NextPage } from "next";
import Container from "@mui/material/Container";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import useBasePath from "../../../../../hooks/useBasePath";
import FormCommande from "../../../../../components/materiels/commandes/form/FormCommande";

const Home: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>afficher et ou modifier commande</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>

      <Container maxWidth="xl">
        <FormCommande />
      </Container>
    </BackOfficeLayout>
  );
};

export default Home;
