import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import useBasePath from "../../../../../hooks/useBasePath";
import DetailsBCE from "../../../../../components/materiels/bon_commande_externe/[id]/DetailsBCE"

const DetailsBCEPage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Matériels-articleBCE-details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <DetailsBCE />
      </Container>
    </BackOfficeLayout>
  );
};

export default DetailsBCEPage;
