import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../layouts/backOffice";
import useBasePath from "../../../../hooks/useBasePath";
import FormBonDeVoiture from "../../../../components/materiel_de_transport/bon_de_voiture/add/formBondeVoiture";

const FormBvPage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Bon de Voiture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <FormBonDeVoiture/>
      </Container>
    </BackOfficeLayout>
  );
};

export default FormBvPage;