import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../layouts/backOffice";
import useBasePath from "../../../hooks/useBasePath";
import BonCommandeFournisseurList from "../../../components/materiels/bon_commande_fournisseur"

const Bon_de_Commande: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - bon de commande fournisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <BonCommandeFournisseurList />
      </Container>
    </BackOfficeLayout>
  );
};

export default Bon_de_Commande;