import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../layouts/backOffice";
import useBasePath from "../../../hooks/useBasePath";
import ListCommandeConsommable from "../../../components/fournitures_et_consommables/commande/ListCommandeConsommable"; 

const ListCommandeFournitureConsommable: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Fourniture et Consommable - Commande</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
          <ListCommandeConsommable/>
      </Container>
    </BackOfficeLayout>
  );
};

export default ListCommandeFournitureConsommable;