import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import useBasePath from "../../../../../hooks/useBasePath";
import FormInventaireMateriel from "../../../../../components/materiels/inventaire/form/formInventaire";

const NewInventaire: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Inventaire-ajouter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <FormInventaireMateriel />
      </Container>
    </BackOfficeLayout>
  );
};

export default NewInventaire;