import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import useBasePath from "../../../../../hooks/useBasePath";
import DetailsPVComparaison from "../../../../../components/materiels/pvComparaison/[id]/DetailsPVComparaison";

const DetailsPVComparaisonPage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Fournitures et consommables-article-details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <DetailsPVComparaison />
      </Container>
    </BackOfficeLayout>
  );
};

export default DetailsPVComparaisonPage;
