import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../layouts/backOffice";
import useBasePath from "../../../../hooks/useBasePath";
import HistoriqueDetentionMateriel from "../../../../components/materiels/Detenteur/historique/HistoriqueDetentionMateriel";


const HistoDetenteurMateriel: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Detention- Historique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
            <HistoriqueDetentionMateriel/>
      </Container>
    </BackOfficeLayout>
  );
};

export default HistoDetenteurMateriel;