import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../layouts/backOffice";
import useBasePath from "../../../../hooks/useBasePath";
import BonCommendeExterneForm from "../../../../components/materiels/bon_commande_externe/add/bonCommadeExterneForm";

const CommandePage: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Matériels-bonCommandeExterne-ajouter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <BonCommendeExterneForm />
      </Container>
    </BackOfficeLayout>
  );
};

export default CommandePage;
