import React from "react";
import BackOfficeLayout from "../../../../layouts/backOffice";
import Head from "next/head";
import { Container } from "@mui/material";
import CreationBonCommande from "../../../../components/materiels/bon_de_commande/creer/CreationBonCommande";
import useBasePath from "../../../../hooks/useBasePath";

const CreateBonCommande = () => {
	const basePath = useBasePath();
	return (
		<BackOfficeLayout>
			<Head>
				<title>Logistiques - bon de commande - creer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href={`${basePath}/favicon.ico`} />
			</Head>
			<Container maxWidth="xl">
				<CreationBonCommande />
			</Container>
		</BackOfficeLayout>
	);
};

export default CreateBonCommande;
