import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../layouts/backOffice";
import useBasePath from "../../../../hooks/useBasePath";
import CreationBonCommande from "../../../../components/materiels/bon_de_commande/creer/CreationBonCommande";


const FormulaireDeCreationBonCommande: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>Logistiques - Bon de commande - Créer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <Container maxWidth="xl">
        <CreationBonCommande/>
      </Container>
    </BackOfficeLayout>
  );
};

export default FormulaireDeCreationBonCommande;