import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import BackOfficeLayout from "../../../../../layouts/backOffice";
import ListCommande from "../../../../../components/Commande/ListeCommande";
import useBasePath from "../../../../../hooks/useBasePath";

const Home: NextPage = () => {
  const basePath = useBasePath();
  return (
    <BackOfficeLayout>
      <Head>
        <title>afficher et ou modifier commande</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      
      <Container maxWidth="xl">
        <ListCommande/>
      </Container>
    </BackOfficeLayout>
  );
};

export default Home;
