import React from "react";
import BackOfficeLayout from "../../../../layouts/backOffice";
import Head from "next/head";
import { Container } from "@mui/material";
import useBasePath from "../../../../hooks/useBasePath";
import CreationBonCommandeFournisseur from "../../../../components/materiels/bon_commande_fournisseur/creer/createBonCommandeFournisseur";

const CreateBonCommandeFournisseur = () => {
	const basePath = useBasePath();
	return (
		<BackOfficeLayout>
			<Head>
				<title>Logistiques - bon de commande Fournisseur- creer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href={`${basePath}/favicon.ico`} />
			</Head>
			<Container maxWidth="xl">
				<CreationBonCommandeFournisseur />
			</Container>
		</BackOfficeLayout>
	);
};

export default CreateBonCommandeFournisseur;
